#lang racket
(define noun-list (list 'dog 'cat 'student 'professor 'book 'computer))
(define verb-list (list 'ran 'ate 'slept 'drank 'exploded 'decomposed))
(define adjective-list (list 'red 'slow 'dead 'pungent 'over-paid 'drunk))
(define adverb-list (list 'quickly 'slowly 'wickedly 'majestically))

(define (sentence)
  (append (append (list 'the) (noun-phrase)) (verb-phrase))
)

(define (pick-random lst)
  (list-ref lst (random (length lst) ))
)

(define (a-noun)
  (list (pick-random noun-list))
  )
(define (a-verb)
  (list (pick-random verb-list))
  )
(define (an-adverb)
  (list (pick-random adverb-list))
  )
(define (an-adjective)
  (list (pick-random adjective-list))
  )
(define (either a b)
  (if (= (random 2) 1) (a) (b) )
)
(define (noun-phrase)
  (either a-noun (lambda () (append (an-adjective) (noun-phrase))))
)
(define (verb-phrase)
  (either a-verb (lambda () (append (a-verb) (an-adverb))))
)